### ISSUE TITLE
Using this library for RT60 measurements

### ISSUE THREAD

**Issue by Ralph-Imholz** [snickell/impulse-response#1]
Hello,

Could this library be used to perform RT60 measurements. I'm a web developer for an acoustic products company. We sell acoustic panels/absorbers and until now we've been working with a third party Room Impulse Response and RT60 measurements app, and we are now researching the possibility to build such an app in-house, for all kinds of reasons.

Being a web developer, I was looking into Web Audio solutions for this problem, and I stumbled upon this library.

I am mostly a front-end developer, and this is my first time diving into the Web Audio API, and I was wondering if this library would be of use to me!

I'd love hearing from you!

Kind Regards, Ralph

**Comment by snickell** [comment]
Hi Ralph, this should work to produce an accurate impulse response for a room. I don't know a lot about what RT60 signifies as a standard, but you could take the initial sample from the IR, and see at what time the IR no longer crosses -60dB from the first loud sample. Patches happily accepted ;-)

**Comment by snickell** [comment]
@Ralph-Imholz The IR produced by this should be completely accurate for doing measurements, I just don't know the details of what an RT60 measurement is, if that makes sense?

**Comment by snickell** [comment]
So this may or may not be helpful since its sort of written in a DSP style, but I just looked up RT60: https://dsp.stackexchange.com/questions/17121/calculation-of-reverberation-time-rt60-from-the-impulse-response

This library is a very suitable way to accomplish the first bit, namely "get an impulse response" part, i.e.
```After getting the impulse response ℎ(𝑡) of your acoustic space```

**Comment by Ralph-Imholz** [comment]
Basically what we're trying to do is this:

1. Have a client go to our website on their smartphone.
2. Record a short bit of audio with the smartphone microphone.
3. During the recording, we instruct the client to create an impulse (clap their hands or pop a balloon).
4. We analyze the recording to see how long it takes for the impulse to drop from its peak back to silent.

The reason why I want to do this in JavaScript (even though a native app might be more optimal for this) comes down to the fact that I'm a web dev that has no experience developing native apps and I was trying to see if I could make something like this on my own.

We do these kind of measurements already using professional audio tools, but they are expensive (iPad/iPhone with third party microphone) and they are actually too accurate for 95% of our clients. It's also required that one of our sales reps visits the client, and with a web app the client could do it themselves.

I hope this gives more insight into my situation!

**Comment by snickell** [comment]
@Ralph-Imholz this library does a "sine sweep" which is a more accurate way of measuring the impulse response (IR = "sound of a gunshot in the room") than a clap. You'd need to write javascript on your end to decide where in the WAV file the RT60 point is.
